# Generated by Django 2.2.6 on 2020-04-14 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_auto_20200414_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoclave',
            name='certificate_timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 4, 14, 11, 35, 36, 573413)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoclave',
            name='due',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='certificate_timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 4, 14, 11, 35, 46, 550101)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='due',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='genericcalibration',
            name='certificate_timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 4, 14, 11, 35, 51, 606273)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericcalibration',
            name='due',
            field=models.DateField(blank=True),
        ),
    ]
