# Generated by Django 2.2.6 on 2020-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_auto_20200414_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoclave',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='autoclave',
            name='humidity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='autoclave',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='autoclave',
            name='temperature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='balance',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='humidity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='balance',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='temperature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='genericcalibration',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='genericcalibration',
            name='humidity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='genericcalibration',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='genericcalibration',
            name='temperature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
