# Generated by Django 2.2.6 on 2020-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_auto_20200414_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoclave',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericcalibration',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
