# Generated by Django 2.2.6 on 2020-04-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_auto_20200414_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoclave',
            name='certificate_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='balance',
            name='certificate_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='genericcalibration',
            name='certificate_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='autoclave',
            name='certificate_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='certificate_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='genericcalibration',
            name='certificate_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
