from calibration import views
from django.urls import path

appname = 'calibration'

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('create-customer/', views.CustomerCreateView.as_view(), 
        name='create-customer'),
    path('create-profile/', views.ProfileCreateView.as_view(), 
        name='create-profile'),
    path('reset-profile/', views.PasswordResetView.as_view(), 
        name='reset-profile'),
    path('change-password/', views.PasswordChangeView.as_view(), 
        name='change-password'),
    path('customer-list/', views.CustomerListView.as_view(), 
        name='customer-list'),
    path('update-customer/<int:pk>', views.CustomerUpdateView.as_view(), 
        name='update-customer'),
    path('customer-details/<int:pk>', views.CustomerDetailView.as_view(), 
        name='customer-details'),
    path('create-standard/', views.StandardCreateView.as_view(), 
        name='create-standard'),
    path('standard-list/', views.StandardListView.as_view(), 
        name='standard-list'),
    path('update-standard/<int:pk>', views.StandardUpdateView.as_view(), 
        name='update-standard'),
    path('standard-details/<int:pk>', views.StandardDetailView.as_view(), 
        name='standard-details'),
    path('calibration-list/', views.CalibrationListView.as_view(), 
        name='calibration-list'),
    path('balance-calibration-list/', views.BalanceCalibrationListView.as_view(), 
        name='balance-calibration-list'),
    path('balance-calibration-detail/<int:pk>/', views.BalanceDetailView.as_view(), 
        name='balance-calibration-detail'),
    path('balance-pdf/<int:pk>/', views.BalancePDFView.as_view(), 
        name='balance-pdf'),
    path('autoclave-pdf/<int:pk>/', views.AutoclavePDFView.as_view(), 
        name='autoclave-pdf'),
    path('generic-pdf/<int:pk>/', views.GenericPDFView.as_view(), 
        name='generic-pdf'),
    path('autoclave-calibration-detail/<int:pk>/', views.AutoclaveDetailView.as_view(), 
        name='autoclave-calibration-detail'),
    path('calibration-detail/<int:pk>/', views.GenericDetailView.as_view(), 
        name='calibration-detail'),
    path('generate-certificate/<str:type>/<int:pk>/', views.GenerateCertificateView.as_view(), 
        name='generate-certificate'),
    path('autoclave-calibration-list/', views.AutoclaveCalibrationListView.as_view(), 
        name='autoclave-calibration-list'),
    path('upload/', views.UploadView.as_view(), 
        name='upload'),
    path('upload-standards/', views.upload_standards, 
        name='upload-standards'),
    path('upload-calibrations/', views.upload_calibrations, 
        name='upload-calibrations'),
]
